spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 763433673008-me7v73cih8g7a3qf3agl51fpitcen5js.apps.googleusercontent.com
            client-secret: w6WySmhZFC3X4rJrvjQSRGTT
            redirect-uri: http://localhost:8090/login/oauth2/code/google
            scope:
              - profile
              - email
            authorization-grant-type: authorization_code

          naver:
            client-id: QlsEpBY0sEHx8MKirMX9
            client-secret: qoaI880Hv6
            scope:
              - name
              - email
              - profile_image
            redirect-uri: http://localhost:8090/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-name: Naver

          kakao:
            client-id: 939cf240739da8fa5908d7fb69668353
            client-secret: E4w8f2AwTne3lxGBzImtjmKocvrM3ETa
            redirect-uri: http://localhost:8090/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
